### ISSUE TITLE
Handle geoblocking

### ISSUE THREAD

**Issue by fabi321** [DzenanJupic/rustube#15]
I tried to fetch information for https://www.youtube.com/watch?v=hQ4n4zHdrwA and it returned a `watch html did not contain a PlayabilityStatus` when fetched from Germany. As far as I can tell from the corosponding youtube site it's geoblocked

**Comment by DzenanJupic** [comment]
@fabi321 danke, dass du ein Issue aufgemacht hast und servus aus München 😁! 

Bypassing geoblocking is actually one of the things, that's not implemented yet. When I first wrote `rustube` I didn't manage to find any geo-blocked videos, so I skipped that part.

Also, when you look at `pytube` (`./pytube/__main__.py:260`)
```python
if extract.is_region_blocked(self.watch_html):
    raise exceptions.VideoRegionBlocked(video_id=self.video_id)
```
it seems like that's not straight forward.

As far as I know, `youtube-dl` has a method for downloading region geo-blocked content, but I'm not quite sure.

**Comment by fabi321** [comment]
It would be nice if it would return a more meaningful error than the generic watch `html did not contain a PlayabilityStatus`.
If I try to download this video with youtube-dl it gives me an error: video unavailable.
So it seems like even youtube-dl is unable to bypass this.

**Comment by DzenanJupic** [comment]
Ok in that case I doubt that we will find a quick fix for downloading videos that are geo-blocked. But I can quickly fix the deserialization problem.

**Comment by DzenanJupic** [comment]
small update: 
`rustube v0.2.7` is now published. This update also contains the changes regarding this issue. `rustube-cli` on the other hand is not at version `0.2.7` yet.
Since it's a minor version upgrade, `rustube-cli` will pick up the new version anyway, as long it's not installed with the `--locked` flag.
To reinstall `rustube-cli` using the updated `rustube` library just run `cargo +nightly install rustube-cli -f`.
