### ISSUE TITLE
Fetch video info for offline livestreams

### ISSUE THREAD

**Issue by fabi321** [DzenanJupic/rustube#18]
I wanted to fetch the `VideoDetails`/`VideoInfo` struct for an offline stream and realized, that `fetch` is pub but fails on `Self::check_availability` and `get_video_info` is private so I can't call it. By looking into the json arguments from an offline live stream I don't think they're missing anything except for the streams themselves.

**Comment by DzenanJupic** [comment]
@fabi321 thank you for the proposal. 
Fetching the video information of videos that cannot be downloaded is actually something I didn't think of, but it seems more than reasonable.

I just checked whether or not leaving the availability check away would solve the problem. It doesn't break anything but makes the error message less clear when a video is unavailable. So I don't want to just eliminate that check.
On the other hand, this would also eliminate deserializing `PlayabilityStatus` twice, when it's not required.

I think for now I'll just add a `fetch_unchecked` method to `VideoFetcher` since it's not a breaking change, and I want to redesign the API in general before jumping to `0.3`.
