### ISSUE TITLE
Stream URLs for direct viewing

### ISSUE THREAD

**Issue by Darksecond** [DzenanJupic/rustube#4]
Is there an API in rustube that allowed me to get the stream URL directly, so I can view it directly in a `<video>` tag?
Youtube-dl supports this with the `-g` flag.

**Comment by DzenanJupic** [comment]
@Darksecond this is defeinetly something that should exist, and I will implement it within the next few days.

As a temporary fix you can run `rustube fetch <ID>` and look for the ` signature_cipher` field of the stream you want. There you will find the subfield `url`, which contains a `host`, a `path`, and a `query`. Using those fields, you can build an URL.

**Comment by DzenanJupic** [comment]
I should add that the output of the CLI is currently just the debug representation (`"{:?}"`) of the Video. This will change with the next version to yaml and JSON, so you can use it with scripts.

> so I can view it directly in a <video> tag
If your plan is to serve the videos using your own server, I highly recommend using the `rustube` library instead of the CLI. It gives you much more control and also allows you to access the URL.

**Comment by DzenanJupic** [comment]
@Darksecond took a bit longer than expected, but with `rustube-cli 0.3.0` it's now possible to get only the stream-urls by running
```
rustube check -l url <identifier>
```

Running only `rustube check <identifier>` will also print out the URLs together with some additional information. It's a shorthand for `rustube check -l "url general video-track audio-track" <identifier>`.


`rustube check --help` gives more information about all the options.
