### ISSUE TITLE
get_video_info broken

### ISSUE THREAD

**Issue by 89z** [DzenanJupic/rustube#40]
~~~
curl -v 'https://www.youtube.com/get_video_info?video_id=5jlI4uzZGjU&eurl=https://youtube.com/watch?iv=5jlI4uzZGjU&sts=18830'
HTTP/2 404
~~~

**Comment by DzenanJupic** [comment]
@89z thank you for opening this issue. Could you please explain what the purpose of this issue is?

**Comment by 89z** [comment]
https://github.com/DzenanJupic/rustube/blob/691be5c52299dc5ec257e7c4512c5519610f869b/src/fetcher.rs#L382-L389

**Comment by DzenanJupic** [comment]
Since commit [2a3a684ced228f73fe9992442eb5f6e54e8ab4e4](https://github.com/DzenanJupic/rustube/commit/2a3a684ced228f73fe9992442eb5f6e54e8ab4e4) / `v0.3.5` we don't activly use that function anymore:

https://github.com/DzenanJupic/rustube/blob/691be5c52299dc5ec257e7c4512c5519610f869b/src/fetcher.rs#L290-L293

We currently generate the `VideoInfo` ourselves by using the `PlayerResponse` from the watch HTML:
https://github.com/DzenanJupic/rustube/blob/691be5c52299dc5ec257e7c4512c5519610f869b/src/fetcher.rs#L243-L265

The reason it's still in the codebase is that `v0.3.5` is just a quick fix. If there are new required query parameters, that make `/get_video_info` work again it will stay, otherwise, we will get rid of it in one of the next versions.
